name: Publish Release
on:
  workflow_dispatch:
    inputs:
      increment:
        description: The type of version bump to perform
        required: false
        type: choice
        options:
          - ""
          - major
          - minor
          - patch
      prerelease:
        description: The type of version bump to perform
        required: false
        type: choice
        options:
          - ""
          - alpha
          - beta
          - rc

jobs:
  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Bump Version
        id: cz
        uses: commitizen-tools/commitizen-action@338bbd841b75aaee6bf5340e1fa12f6ab58ff9ff # 0.27.1
        with:
          increment: ${{ inputs.increment }}
          prerelease: ${{ inputs.prerelease }}
          changelog_increment_filename: release.md
          git_redirect_stderr: true
          push: false

      - name: Push Commit & Tag
        run: git push && git push --tags

      - name: Publish Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
        with:
          body_path: release.md
          tag_name: v${{ steps.cz.outputs.version }}
